# Generated by Django 4.2.7 on 2025-07-15 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=100, verbose_name='Apellido')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('employee_id', models.CharField(max_length=20, unique=True, verbose_name='ID Empleado')),
                ('department', models.CharField(max_length=100, verbose_name='Departamento')),
                ('position', models.CharField(max_length=100, verbose_name='Cargo')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Salario')),
                ('hire_date', models.DateField(verbose_name='Fecha de Contratación')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'ordering': ['-created_at'],
            },
        ),
    ]
